version: '3'
services:
  wefox:
    container_name: wefox
    restart: always
    build: .
    ports:
      - '6379:6379'
      - '27017:27017'
    links:
      - redis
      - mongo
  mongo:
    container_name: mongo
    image: 'mongo'
  redis:
    container_name: redis
    image: 'redis'
